version: '3'

networks:
  backnet:
    driver: bridge

services:
  frontgate:
    image: openresty/openresty
    restart: unless-stopped
    networks:
      - backnet
    volumes:
      # Main config
      - ./frontgate/conf.d:/etc/nginx/conf.d
      # Certbot config
      - ${CERTBOT_DIR}/conf:/etc/letsencrypt
      - ${CERTBOT_DIR}/www:/var/www/certbot
    environment:
      KEYCLOAK_PUBLIC_HOST: ${KEYCLOAK_PUBLIC_HOST}
    command: "/bin/sh -c \"envsubst '$${KEYCLOAK_PUBLIC_HOST}' < /etc/nginx/conf.d/keycloak.conf.template > /etc/nginx/conf.d/keycloak.conf && nginx -g 'daemon off;'\""
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - keycloak
  postgres:
    image: postgres
    volumes:
      - ${DB_DIR}:/var/lib/postgresql/data
    networks:
      - backnet
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}  
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ${CERTBOT_DIR}/conf:/etc/letsencrypt
      - ${CERTBOT_DIR}/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - backnet  
  keycloak:
    image: jboss/keycloak:latest
    volumes:
      - ./keycloak/theme:/opt/jboss/keycloak/themes/HealthID
      - ./authenticator/build/libs/authenticator.jar:/opt/jboss/keycloak/standalone/deployments/authenticator.jar
    networks:
      - backnet
    depends_on:
      - postgres
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_LOGLEVEL: DEBUG
      ROOT_LOGLEVEL: INFO
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_SCHEMA: public
      DB_PASSWORD: ${DB_PASSWORD}
  keycloak-config:
    build: ./keycloak-config/
    networks:
      - backnet
    volumes:
      - ./keycloak-config:/code  
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_BASE_URL: ${KEYCLOAK_BASE_URL}
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    depends_on:
      - keycloak
  
    
    
